### ISSUE TITLE
Radeon Pro W5500 Via Thunderbolt

### ISSUE THREAD

**Issue by gtrooper** [SchmockLord/Gigabyte-Z590i-Vision-D-11900k#1]
Hello SchmockLord, Just a quick question regarding GPU connectivity. The only GPU you use now is EXTERNAL ? How good this actually work ? Are you able to get proper boot screen image when you have W5500 connected via Thunderbolt ? Does The Boot Picker works normally and are you able to boot Windows 10 with no problems with this external GPU Setup ?  I am asking because I need the single PCIe 4.0 x16 slot of this board for a RAID NVME Card and wanna confirm if there are any issues before I proceed with this setup ! Thank you !

**Comment by SchmockLord** [comment]
Overall it works well. But if you can avoid this I would prefer having the GPU internal and only one. But as I am also gaming and use Windows a lot, I use my 3090 internal.

**Comment by gtrooper** [comment]
> Overall it works well. But if you can avoid this I would prefer having the GPU internal and only one. But as I am also gaming and use Windows a lot, I use my 3090 internal.
> 
> Until the OC Bootpicker apears I use the 3090 and DP1-IN on the monitor. As soon as I hear that the Thunderbolt GPU (fans start spinng short) is connected, I switch to DP2-IN. Which is connected to the eGPU.

Oh, I see ! Thanks for the explanation !
