### ISSUE TITLE
No Bluetooth Working

### ISSUE THREAD

**Issue by DarioBogus** [SchmockLord/Gigabyte-Z590i-Vision-D-11900k#14]
Hi there. Using same config as you, BCM94360NG included (except for the GPU, i'm using an internal RX6800XT).
After applying 0.7.2 config there's no bluetooth working but only wifi.

Tried to understand why searching in the config.plist but nothing. 
Any ideas?

**Comment by DarioBogus** [comment]
Ok. Step ahead. 
Bluetooth stops working applying the new USB map through SSDT-UIAC-Z590i-VisionD.aml in ACPI folder and config.plist and USbInjectAll.kext in Kext folder and config.plist
BTW still don't know why stops working.

**Comment by DarioBogus** [comment]
Another step. 
Figured out that in the new USBmap there's not HS14, wich is used by BRCM20702 Hub for Bluetooth funcionality.

**Comment by SchmockLord** [comment]
Will fix that tonight.

**Comment by SchmockLord** [comment]
Should be working with current release.
