### ISSUE TITLE
USB Big Sur 11.5.2

### ISSUE THREAD

**Issue by EmmaBentley** [SchmockLord/Gigabyte-Z590i-Vision-D-11900k#18]
First of all, allow me to thank you for your amazing work on this set of texts it has allowed me to finally use my machine as a mac with my 6800XT and allow me to run my business properly, i am an X Plane 11 Airport developer  so thank you so much for all the work you do, now ,i am using your most recent release but i have noticed that half the USB ports are not working on 11.5.2 the USB 2 ports don't work, with anything plugged into them which is a real shame, is there any chance you have developed a fix at all ? 

thanks so much for your work once again i cant stress this enough

Emma x

**Comment by desisn** [comment]
What is your motherboard? Z590i Vision D or Z590 Vision D? There is a difference and you need to remap the USB ports and include your own SSDT-UIAC.aml that you create via Hackintool or the USBMap (https://github.com/corpnewt/USBMap) tool. There is some good tutorials for USB mapping via Hackintool on YouTube.

**Comment by EmmaBentley** [comment]
my apologies for the late reply! it's the same Motherboard as you, I misread the information you provided it was my fault, I apologize. I did however wanted to ask if you have pictures of where the wifi card is so I can replace mine in the future, as I couldn't see the location of it, Thanks and once again, amazing work on this project!
