### ISSUE TITLE
Ethernet is not working

### ISSUE THREAD

**Issue by robertop23** [SchmockLord/Gigabyte-Z590i-Vision-D-11900k#29]
I added LucyRTL8125Ethernet and I'm getting:
 OC: Prelinked injection LucyRTL8125Ethernet.kext (LucyRTL8125Ethernet.kext) - Success

But inside the installer there is no en0 device, no Internet, any ideas?

Also, I'm from Linux, how I can get the correct pci path and values to be added to deviceProperties?

**Comment by MiddlemanTM** [comment]
If you add the kext you also need to add the Intel ethernet device to the Device Properties list like this to enable it:

![Screen Shot 2021-11-23 at 11 57 32 AM](https://user-images.githubusercontent.com/78093030/142969399-7098516f-27b4-4c92-85c2-f61e8cce18ef.png)

**Comment by andreszerocross** [comment]
This repository give false information,,

This board is using Intel 2.5GB ethernet not REALTEK 2.5GB ethernet. LucyRTL8125Ethernet won't work. This is missinformation. cc @SchmockLord

**Comment by SchmockLord** [comment]
I know. It is an Intel 2.5Gbit. I don't have any issue with the Intel 2.5Gbit with the EFI in the repository but it depends on the macOS you're using. I use Monterey.
