### ISSUE TITLE
no cpu sensors

### ISSUE THREAD

**Issue by kenyroot** [SchmockLord/Gigabyte-Z590i-Vision-D-11900k#36]
iStat program not sensors cpu in [v23](https://github.com/SchmockLord/Gigabyte-Z590i-Vision-D-11900k/releases/tag/v23)
work in [v19](https://github.com/SchmockLord/Gigabyte-Z590i-Vision-D-11900k/releases/tag/v19)

**Comment by SchmockLord** [comment]
Just add SMCProcessor.kext. I don't need it and like it lightweight.

**Comment by kenyroot** [comment]
file added in package  but not included in config.plist
it seems strange

**Comment by SchmockLord** [comment]
Shit, I see it. I thought I only included VirtualSMC. Thanks for pointing that out. Alright, then I will add the Satellite-Kexts.

**Comment by SchmockLord** [comment]
Reuploaded. Thanks.
